server:
  port: 8002

spring:
  application:
    name: cloud-consumer-Feign-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka