server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Horace-wang/spring_cloud_config.git
          search-paths:
            - spring_cloud_config
          username: Horace-wang
          password: lh199824
      label: main


eureka:
  instance:
    hostname: cloud-config-center
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka